### ISSUE TITLE
fyi : versions >1.0.3 are broken

### ISSUE THREAD

**Issue by ar1ja** [tabotkevin/flask_limit#5]
not a clue what changed, but versions above 1.0.3 refuse to import, i get a `ModuleNotFoundError` if i use a version above `1.0.3`, so currently i am sticking with `Flask_Limiter==1.0.3` might wanna check out the problem :)

( i upgraded and noticed it )

**Comment by tabotkevin** [comment]
Thank you so much, I will take a look.

**Comment by tabotkevin** [comment]
It is fixed now, can you please try again, it was a code structure issue base on my configuration setup.cfg.
